### PR TITLE
Fix spawner turning into pig.

### PR DESCRIPTION
**Pull request by PedroMPagani**
Fix spawner turning to PIG due to timing-ticking issues in spawner PlayerInteractListener

### CODE REVIEW

**Comment by PedroMPagani** [comment]
I forgot to remove some debugs from the classes and did in the 2nd commit.

**Comment by PedroMPagani** [comment]
The issue is basically the player interacts in the same tick as placing the spawner, the current tick will change the block type, the next tick the entity changed the type, the player interact listener thinks that the spawner is basically getting changed by an egg, after that, completely returns to the begging state (which was always a pig) since it just got set to the correct type, this type of behavior happens a lot in plugins but it's most likely unpredictable, it has to consider the player skill, and latency of the user too, as well as like this, placing and interacting

**Comment by CorneliusMa** [comment]
Thanks a lot for contributing!

**Comment by PedroMPagani** [comment]
Hey, that's alright, it was merged into the branch fixes btw, just so you don't forget to include it in a future release you do

**Pull request merged**
